name: Deploy Package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Publish upm package
        uses: cdmvision/action-upm-publish@v1.1
        with:
          name: "com.inscept.notarization"
          upmBranch: "upm"
